services:
  db:
    image: postgres
    ports:
      - 5432:5432
    shm_size: 128mb
    # environment:
    #   POSTGRES_USER: svelteapp
    #   POSTGRES_PASSWORD: sv3lt34pp
    #   POSTGRES_DB: db
    env_file:
      - "../.env"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - ./minio:/data
